column_mapping:
  numerical_features:
  - Time
  - V1
  - V2
  - V3
  - V4
  - V5
  - V6
  - V7
  - V8
  - V9
  - V10
  - V11
  - V12
  - V13
  - V14
  - V15
  - V16
  - V17
  - V18
  - V19
  - V20
  - V21
  - V22
  - V23
  - V24
  - V25
  - V26
  - V27
  - V28
  - Amount
  target: Class
data_format:
  header: true
  separator: ','
service:
  calculation_period_sec: 300
  min_reference_size: 100
  monitors:
  - data_drift
  - classification_performance
  moving_reference: false
  reference_path: ./reference.csv
  use_reference: true
  window_size: 100
